# Generated by Django 3.2.12 on 2022-02-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
                ('category_slug', models.SlugField(max_length=250, unique=True)),
                ('category_desc', models.TextField(blank=True)),
                ('category_img', models.ImageField(blank=True, upload_to='Category Gallery')),
            ],
            options={
                'verbose_name': 'category_name',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('product_slug', models.SlugField(max_length=250, unique=True)),
                ('product_desc', models.TextField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.ImageField(blank=True, upload_to='Product Gallery')),
                ('product_stock', models.IntegerField()),
                ('product_availability', models.BooleanField(default=True)),
                ('product_create_time', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('product_name',),
            },
        ),
    ]
